# name of the software
name: Java client library for Digipost API for User Agreements
# current version of the software
version: 1.0
# url of the download button
downloadUrl: https://www.nuget.org/packages/digipost-api-client/
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

baseurl: "/digipost-useragreements-api-client-java"

currentVersion: "1.0"
versions: ["1.0"]

collections:
  v1_0:
      output: true
      permalink: /v1.0/

# list of additional links on the right of the top menu
headerLinks:
  - title: Download library
    url: https://github.com/digipost/digipost-useragreements-api-client-java
  - title: GitHub
    url: https://github.com/digipost/digipost-useragreements-api-client-java
  - title: Digipost
    url: https://www.digipost.no

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/digipost/digipost-useragreements-api-client-java
  - title: Issues
    url: https://github.com/digipost/digipost-useragreements-api-client-java/issues

# header
header:
  color1: "#e32d22"
  color2:
  trianglify: false

# github buttons
githubButton:
  user: digipost
  repo: digipost-useragreements-api-client-java

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: digipost_no

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  account:
  domain:

# DON'T MODIFY
highlight: rouge

gems:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
