# site title
title: Java client library for Digipost API for User Agreements
# current version of the software
version: 4.0.0
# url of the download button
downloadUrl: https://github.com/digipost/digipost-useragreements-api-client-java
# licence of the software
license: The Apache Software License, Version 2.0
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.txt

baseurl: "/digipost-useragreements-api-client-java"

currentVersion: "4.x"
versions: ["4.x", "3.x", "2.x", "1.x"]

collections:
  v1_x:
    output: true
    permalink: /v1.x/
  v2_x:
    output: true
    permalink: /v2.x/
  v3_x:
    output: true
    permalink: /v3.x/
  v4_x:
    output: true
    permalink: /v4.x/

# list of additional links on the right of the top menu
headerLinks:
  - title: Download library
    url: https://github.com/digipost/digipost-useragreements-api-client-java
  - title: GitHub
    url: https://github.com/digipost/digipost-useragreements-api-client-java
  - title: Digipost
    url: https://www.digipost.no

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/digipost/digipost-useragreements-api-client-java
  - title: Issues
    url: https://github.com/digipost/digipost-useragreements-api-client-java/issues

# header
header:
  color1: "#e32d22"
  color2:
  trianglify: false

# github buttons
githubButton:
  user: digipost
  repo: digipost-useragreements-api-client-java

# DON'T MODIFY
highlight: rouge

plugins:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
